export const SET_USER_LOGGED_TYPE = 'SET_USER_LOGGED'

export const CLEAR_USER_LOGGED_TYPE = 'CLEAR_USER_LOGGED'
export const SET_REDIRECT = 'SET_USER_REDIRECT'
export const CLEAR_REDIRECT = 'CLEAR_USER_REDIRECT'