export const LOAD = "CLOSE_FIELD_MAP_LOAD";
export const CLEAR = "CLOSE_FIELD_MAP_CLEAR";
export const SET_VARIABLE = "CLOSE_FIELD_MAP_SET_VARIABLE";
export const SET_VARIABLE_RANGE = "CLOSE_FIELD_MAP_SET_VARIABLE_RANGE";
export const SET_VARIABLES = "CLOSE_FIELD_MAP_SET_VARIABLES";