export const START_LOADING = 'CLOSE_FIELD_LOAD_START_LOADING';
export const LOAD_ERROR = 'CLOSE_FIELD_LOAD_LOAD_ERROR';
export const SHOW = 'CLOSE_FIELD_LOAD_SHOW';
export const CLEAR = 'CLOSE_FIELD_LOAD_CLEAR';


