export const CHANGE_NUMBER_OF_MAPS = "LAYERS_COMPARISON_COMPARISON_CHANGE_NUMBER_OF_MAPS";
export const ADD_MAP = "LAYERS_COMPARISON_COMPARISON_ADD_MAP";
export const START_LOADING_DATA = "LAYERS_COMPARISON_COMPARISON_START_LOADING_DATA";
export const DATA_LOADED = "LAYERS_COMPARISON_COMPARISON_DATA_LOADED";
export const ERROR_LOADING_DATA = "LAYERS_COMPARISON_COMPARISON_ERROR_LOADING_DATA";
export const SET_VARIABLE = "LAYERS_COMPARISON_COMPARISON_SET_VARIABLE";
export const SET_VARIABLE_RANGE = "LAYERS_COMPARISON_COMPARISON_SET_VARIABLE_RANGE";
export const CLEAR = "LAYERS_COMPARISON_COMPARISON_CLEAR";